# Generated by Django 4.1.1 on 2022-09-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Estudiante')),
                ('profesor', models.CharField(max_length=50, verbose_name='Profesor')),
                ('materia', models.CharField(max_length=50, verbose_name='Materia')),
            ],
        ),
    ]
